/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.facebook.drawee;

public final class R {
    public static final class attr {
        public static final int actualImageScaleType = 0x7f020000;
        public static final int actualImageUri = 0x7f020001;
        public static final int backgroundImage = 0x7f020002;
        public static final int fadeDuration = 0x7f020003;
        public static final int failureImage = 0x7f020004;
        public static final int failureImageScaleType = 0x7f020005;
        public static final int overlayImage = 0x7f020006;
        public static final int placeholderImage = 0x7f020007;
        public static final int placeholderImageScaleType = 0x7f020008;
        public static final int pressedStateOverlayImage = 0x7f020009;
        public static final int progressBarAutoRotateInterval = 0x7f02000a;
        public static final int progressBarImage = 0x7f02000b;
        public static final int progressBarImageScaleType = 0x7f02000c;
        public static final int retryImage = 0x7f02000d;
        public static final int retryImageScaleType = 0x7f02000e;
        public static final int roundAsCircle = 0x7f02000f;
        public static final int roundBottomLeft = 0x7f020010;
        public static final int roundBottomRight = 0x7f020011;
        public static final int roundTopLeft = 0x7f020012;
        public static final int roundTopRight = 0x7f020013;
        public static final int roundWithOverlayColor = 0x7f020014;
        public static final int roundedCornerRadius = 0x7f020015;
        public static final int roundingBorderColor = 0x7f020016;
        public static final int roundingBorderPadding = 0x7f020017;
        public static final int roundingBorderWidth = 0x7f020018;
        public static final int viewAspectRatio = 0x7f020019;
    }
    public static final class id {
        public static final int center = 0x7f040000;
        public static final int centerCrop = 0x7f040001;
        public static final int centerInside = 0x7f040002;
        public static final int fitCenter = 0x7f040003;
        public static final int fitEnd = 0x7f040004;
        public static final int fitStart = 0x7f040005;
        public static final int fitXY = 0x7f040006;
        public static final int focusCrop = 0x7f040007;
        public static final int none = 0x7f040008;
    }
    public static final class styleable {
        public static final int[] GenericDraweeHierarchy = { 0x7f020000, 0x7f020002, 0x7f020003, 0x7f020004, 0x7f020005, 0x7f020006, 0x7f020007, 0x7f020008, 0x7f020009, 0x7f02000a, 0x7f02000b, 0x7f02000c, 0x7f02000d, 0x7f02000e, 0x7f02000f, 0x7f020010, 0x7f020011, 0x7f020012, 0x7f020013, 0x7f020014, 0x7f020015, 0x7f020016, 0x7f020017, 0x7f020018, 0x7f020019 };
        public static final int GenericDraweeHierarchy_actualImageScaleType = 0;
        public static final int GenericDraweeHierarchy_backgroundImage = 1;
        public static final int GenericDraweeHierarchy_fadeDuration = 2;
        public static final int GenericDraweeHierarchy_failureImage = 3;
        public static final int GenericDraweeHierarchy_failureImageScaleType = 4;
        public static final int GenericDraweeHierarchy_overlayImage = 5;
        public static final int GenericDraweeHierarchy_placeholderImage = 6;
        public static final int GenericDraweeHierarchy_placeholderImageScaleType = 7;
        public static final int GenericDraweeHierarchy_pressedStateOverlayImage = 8;
        public static final int GenericDraweeHierarchy_progressBarAutoRotateInterval = 9;
        public static final int GenericDraweeHierarchy_progressBarImage = 10;
        public static final int GenericDraweeHierarchy_progressBarImageScaleType = 11;
        public static final int GenericDraweeHierarchy_retryImage = 12;
        public static final int GenericDraweeHierarchy_retryImageScaleType = 13;
        public static final int GenericDraweeHierarchy_roundAsCircle = 14;
        public static final int GenericDraweeHierarchy_roundBottomLeft = 15;
        public static final int GenericDraweeHierarchy_roundBottomRight = 16;
        public static final int GenericDraweeHierarchy_roundTopLeft = 17;
        public static final int GenericDraweeHierarchy_roundTopRight = 18;
        public static final int GenericDraweeHierarchy_roundWithOverlayColor = 19;
        public static final int GenericDraweeHierarchy_roundedCornerRadius = 20;
        public static final int GenericDraweeHierarchy_roundingBorderColor = 21;
        public static final int GenericDraweeHierarchy_roundingBorderPadding = 22;
        public static final int GenericDraweeHierarchy_roundingBorderWidth = 23;
        public static final int GenericDraweeHierarchy_viewAspectRatio = 24;
        public static final int[] SimpleDraweeView = { 0x7f020001 };
        public static final int SimpleDraweeView_actualImageUri = 0;
    }
}
